Algoritmo "pag66exJ"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Santos
// Descrição   : Conversão de Celcius para Fahrenheit de 10 em 10
// Data atual  : 19/09/2025
Var
   // Seção de Declarações das variáveis
   c : inteiro
   f : real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para c de 10 ate 100 passo 10 faca
      f <- ((9*c)+160)/5
      escreval(c, "°C = ", f, "°F")
   fimpara


Fimalgoritmo